puts "Destroying previous data..."

SavedPlace.destroy_all
Place.destroy_all
User.destroy_all

puts "Creating Users..."

user1 = User.create(name: "Johannes", username: "Jojo", email: "jojo@test.net", password: "test")
user2 = User.create(name: "Onelis", username: "onelisyarid", email: "onelisyarid@test.net", password: "test")
user3 = User.create(name: "Ryan", username: "atom", email: "atom@test.net", password: "test")

puts "Creating Places..."

place1 = Place.create(name: "Faro Los Morrillos", image: "https://lh5.googleusercontent.com/p/AF1QipMGjgoFJJ0A_AsGqQ36xBtsYu6dv32PQnh-ZeW8=w408-h272-k-no", location: "WRM5+F4C, Rojo Cabo, Cabo Rojo, Puerto Rico", description: "This prominent lighthouse stands atop 200-ft. cliffs making an iconic silhouette on the skyline.", restaurant: false, tourist_loc: true)
place2 = Place.create(name: "Playuela Beach", image: "https://lh5.googleusercontent.com/p/AF1QipPH1QKhS-v0F0WvR0deNe5AqrE6iiUxnpw2deR2=w408-h272-k-no", location: "WRP5+953, Unnamed Road, Cabo Rojo, Puerto Rico", description: "Isolated, picturesque sandy beach with views of a lighthouse atop red limestone cliffs.", restaurant: false, tourist_loc: true)
place3 = Place.create(name: "Annie's Place", image: "https://lh5.googleusercontent.com/p/AF1QipM1V-3StZe1h1ylNGxnGEilPoS6d8UcCmN_cP2d=w408-h306-k-no", location: "3.0 Km, 3301 PR-3301, Boquerón, 00622, Puerto Rico", description: "Beachside restaurant with a stunning view and amazing food.", restaurant: true, tourist_loc: true)
place4 = Place.create(name: "Lechonera El Combate", image: "https://lh5.googleusercontent.com/p/AF1QipO1AqfgkWdo_qK-cCAGpkZINifkOWxUtFWbRjfo=w408-h306-k-no", location: "XRH7+9M4, PR-3301, Boquerón, Cabo Rojo 00623, Puerto Rico", description: "Bar/restaurant at the entrance of a 2 mile road that leads to a beautiful beach.", restaurant: true, tourist_loc: false)
place5 = Place.create(name: "Los Chapines", image: "https://lh5.googleusercontent.com/p/AF1QipOYjU09sfGRl2r7apKEkyv_WR7eBa8ZJ73_NHRZ=w408-h307-k-no", location: "XQHP+WJW, Cll 2, Cabo Rojo, 00623, Puerto Rico", description: "Quaint seafood restaurant a few steps away from the beach.", restaurant: true, tourist_loc: false)
place6 = Place.create(name: "Flavia y Gule", image: "https://lh5.googleusercontent.com/p/AF1QipNqlgsiMsmAbnGzqNnIJkBj68gADf1w9aU-ELTb=w408-h306-k-no", location: "2R2V+8QV, Boquerón, Cabo Rojo 00623, Puerto Rico", description: "Small restaurant that specializes in typical puerto rican comfort food.", restaurant: true, tourist_loc: false)
place7 = Place.create(name: "Playa Boqueron", image: "https://lh5.googleusercontent.com/p/AF1QipMQWDbeD9UJmZ38LHHGyvwbhpJI8cPhzHGRu86R=w408-h544-k-no", location: "Cabo Rojo 00623, Puerto Rico", description: "Tranquil beach bordered by palm trees offering swimming, sunbathing & panoramic views.", restaurant: false, tourist_loc: true)
place8 = Place.create(name: "Papa's Pizza", image: "https://lh5.googleusercontent.com/p/AF1QipNfwSXy0U93NevFY6aAfangCBAY5zvCbTJ1dvMu=w513-h240-k-no", location: "#49 Cll Rios Rivera, Cabo Rojo, 00623, Puerto Rico", description: "Award winning pizzeria in the southern part of the island.", restaurant: true, tourist_loc: true)
place9 = Place.create(name: "Rest. Brisas del Mar", image: "https://lh5.googleusercontent.com/p/AF1QipOuqGv1ETX5WGqWn3FRrqRtPqycgQ7_wzIDlqBC=w408-h306-k-no", location: "Carretera 308 #1134, Puerto Real, 00623, Puerto Rico", description: "Seaside restaurant with amazing seafood and an even more amazing view.", restaurant: true, tourist_loc: false)
place10 = Place.create(name: "Barril Sin Fondo", image: "https://lh5.googleusercontent.com/p/AF1QipNevtlurO3Edojor3wfcNN9LIPnRFx-9xWfg_fh=w507-h240-k-no", location: "Edificio Roig, 102 Calle de la Candelaria, Mayagüez, 00680, Puerto Rico", description: "Unique bar/restaurant with amazing food, one of a kind drinks and a great ambiance.", restaurant: true, tourist_loc: false)
place11 = Place.create(name: "Bartopia Gastrobar", image: "https://lh5.googleusercontent.com/p/AF1QipNYtwKwa5SkutzyYKbzOoIcXgPKs3J6aXF5OzH-=w408-h306-k-no", location: "Esquina Iglesia, 70 Calle E Ramos Antonini, Mayagüez, 00680, Puerto Rico", description: "One of a kind brunch spot with very unique and great tasting food and drink.", restaurant: true, tourist_loc: false)
place12 = Place.create(name: "Viapias Pizza", image: "https://lh5.googleusercontent.com/p/AF1QipPx5TtHsPvFx7PsgZ4-lkT6jGXnM2O92YKEAHjE=w408-h408-k-no", location: "6V42+J92, C. Méndez Vigo, Mayagüez, 00680, Puerto Rico", description: "Italian food with a twist.", restaurant: true, tourist_loc: false)
place13 = Place.create(name: "Cinco de Maya", image: "https://lh5.googleusercontent.com/p/AF1QipP3DlY6j3KqpN_5Bticw3Nn1sCo5t6mh_pdypG1=w426-h240-k-no", location: "75-81 Calle de la Candelaria, Mayagüez, 00680, Puerto Rico", description: "Mexican food with a little puerto rico sprinkled in.", restaurant: true, tourist_loc: false)
place14 = Place.create(name: "El Meson Sandwiches", image: "https://lh5.googleusercontent.com/p/AF1QipNN3fLBsJKDeg-WS7gsYCVIuHNNGUAwvuwklcQw=w426-h240-k-no", location: "University Plaza Marginal Carr. 2, Av. Eugenio María de Hostos, Mayagüez, 00682, Puerto Rico", description: "Franchise sandwich place typically only found in Puerto Rico or some sourthern states.", restaurant: true, tourist_loc: false)
place15 = Place.create(name: "Los Gapo Sandwiches", image: "https://lh5.googleusercontent.com/p/AF1QipNoBecsBPzcxaCY4Yecb1GndjDKYVytV5vPDZmi=w408-h306-k-no", location: "PR 2 Km 138.5, Aguada, 00602, Puerto Rico", description: "Fast, delicious sandwiches and a great spot to hang out after a night of partying.", restaurant: true, tourist_loc: false)
place16 = Place.create(name: "El Faro de Rincon", image: "https://lh5.googleusercontent.com/p/AF1QipPLlTBL7xav5glQLpTn11tvo7LMPr6gDccVEug4=w408-h544-k-no", location: "9P6H+QM Rincon, Rincón, Puerto Rico", description: "Beautiful lighthouse right out of a movie.", restaurant: false, tourist_loc: true)
place17 = Place.create(name: "Domes Beach", image: "https://lh5.googleusercontent.com/p/AF1QipNI2qGzGX5LJ9u1YutY5Lo7B7DrIenUoFrDLS-R=w408-h306-k-no", location: "Rincon, 00602, Puerto Rico", description: "Beautiful beach with amazing views.", restaurant: false, tourist_loc: true)
place18 = Place.create(name: "Cafelados", image: "https://lh5.googleusercontent.com/p/AF1QipOXLIJVD1NNOSSkS-ipKJmxa_Wde6Sxb-OkQWSq=w408-h306-k-no", location: "Carr 442 Km 0.8 Kiosko #4 Sector, 4 P.º Real Marina, Aguadilla Pueblo, 00603, Puerto Rico", description: "Best coffee around, similar to starbucks but cheaper and better.", restaurant: true, tourist_loc: false)
place19 = Place.create(name: "Crash Boat Beach", image: "https://lh5.googleusercontent.com/p/AF1QipOvCFYopiWJU6aDBvip3nMKKCafjW1zPEqBbTQ4=w408-h333-k-no", location: "Borinquen, Aguadilla, Puerto Rico", description: "Picturesque sandy beach known for its clear water, diving dock, food stalls & festive atmosphere.", restaurant: false, tourist_loc: true)
place20 = Place.create(name: "Surfers Beach", image: "https://lh5.googleusercontent.com/p/AF1QipNe0nqHe8teJe2wwo7bDwmcmXa24n-WD20EVjkR=w408-h306-k-no", location: "GV45+2CM, Cliff Rd, Maleza Baja, Aguadilla, Puerto Rico, Aguadilla 00603, Puerto Rico", description: "Rocky beach with some sandy areas and murals.", restaurant: false, tourist_loc: true)
place21 = Place.create(name: "Cofo's Pizza", image: "https://lh5.googleusercontent.com/p/AF1QipMsi4Ei80nJLIIdFW6ePfuLJVditO0d7KoyTLwM=w408-h544-k-no", location: "GV2F+R8R, Maleza Alta, Aguadilla, Puerto Rico, Aguadilla 00603, Puerto Rico", description: "Pizza truck, with some of the best and most inexpensive pizza you will find.", restaurant: true, tourist_loc: false)
place22 = Place.create(name: "Senpai Ramen", image: "https://lh5.googleusercontent.com/p/AF1QipNHdk9H18lccfyRQ1m7H2DQ0Rcm0JbQ6Vmtc3kD=w507-h240-k-no", location: "PR-110 Km. 32.0, Maleza Alta, Aguadilla, Puerto Rico, Aguadilla 00603, Puerto Rico", description: "One of the only ramen and noodle shops on the island, delicious.", restaurant: true, tourist_loc: false)
place23 = Place.create(name: "Ricomini Bakery", image: "https://lh5.googleusercontent.com/p/AF1QipPAKwFEqyCW_PM0QzsR2OjC7YLo--9pbUePSQZw=w493-h240-k-no", location: "FX9G+V6Q, Guerrero, Isabela, Puerto Rico, Isabela 00662, Puerto Rico", description: "Franchised bakery on the island with delicious pastries, sandwiches, cakes and puerto rican food.", restaurant: true, tourist_loc: false)
place24 = Place.create(name: "Don Frappe y Maceta", image: "https://lh5.googleusercontent.com/p/AF1QipOmOYwKbjNepKhkE-tCldmlX-GD9SYvHC3MXQn_=w408-h306-k-no", location: "8V72+34V, Añasco, 00610, Puerto Rico", description: "Huge compound with many different types of food and drink as well as entertainment.", restaurant: true, tourist_loc: true)
place25 = Place.create(name: "La Parguera", image: "https://lh5.googleusercontent.com/p/AF1QipOgHrQo9gl2NZiGrljGzNnsEpDVaRyapJx9BeLu=w504-h240-k-no", location: "84 C. Ángel Luis López, Lajas, 00667, Puerto Rico", description: "Shoreside park with active nights. Very famous location due to its bioluminescent bay.", restaurant: true, tourist_loc: true)
place26 = Place.create(name: "Playa Montones", image: "https://lh5.googleusercontent.com/p/AF1QipNOCbFkjFUkn2MLUOqTUfqFEWNrf0bhoZDYJISX=w408-h306-k-no", location: "PR-466, Isabela 00662, Puerto Rico", description: "Shallow beach on the north side of the island with beautiful waves and views.", restaurant: false, tourist_loc: true)
place27 = Place.create(name: "RicoS", image: "https://lh5.googleusercontent.com/p/AF1QipPSMhW9TilUa2Lla12hIAqpncbIPgMLSxNgltMk=w426-h240-k-no", location: "1 PR-107, Aguadilla Pueblo, Aguadilla 00603, Puerto Rico", description: "Brunch spot with an amazing selection of food and not too far from the beach.", restaurant: true, tourist_loc: false)
place28 = Place.create(name: "Bocata Smokehouse", image: "https://lh5.googleusercontent.com/p/AF1QipPDvxnjHVaXaWELTi4Zkv18e62wQ7LV-DC_aXdT=w426-h240-k-no", location: "PR-681, Arecibo, 00612, Puerto Rico", description: "Shoreside restaurant with amazing puerto rican comfort foods as well as typical island dishes.", restaurant: true, tourist_loc: false)
place29 = Place.create(name: "Gustitos", image: "https://lh5.googleusercontent.com/p/AF1QipOVLc_RoWP9p6jazWn1OGJ5FphgjZO07qtGopHF=w408-h306-k-no", location: "PR-100 km 5.7, Cabo Rojo, 00623, Puerto Rico", description: "Inexpensive but very good comfort food and ice cream.", restaurant: true, tourist_loc: false)
place30 = Place.create(name: "Las Cascadas", image: "https://lh5.googleusercontent.com/p/AF1QipMFMdIqJVgyfmY4RoODkXD2APQoGsrsxlYMMuxy=w426-h240-k-no", location: "2 Puerto Rico, Aguadilla Pueblo, Aguadilla 00603, Puerto Rico", description: "Expansive aquatic amusement park featuring multiple water slides, a lazy river & a kiddie pool.", restaurant: false, tourist_loc: true)

puts "Done Seeding!"